services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ../../models:/app/models
    depends_on:
      - fastapi